language: php

php:
  - 5.3

before_script:
  - ./bin/travis-init.sh
  - "export SYMFONY=`pwd`/lib/vendor/symfony/lib/"

script:
  - php test/unit/SortableTest.php
  - php test/unit/SortableBatchTest.php
  - php test/unit/SortableUniqueByTest.php

env:
 - DB=postgre SYMFONY_REF=origin/1.4
 - DB=mysql SYMFONY_REF=origin/1.4
 - DB=sqlite SYMFONY_REF=origin/1.4
 - DB=postgre SYMFONY_REF=origin/1.3
 - DB=mysql SYMFONY_REF=origin/1.3
 - DB=sqlite SYMFONY_REF=origin/1.3
 - DB=postgre SYMFONY_REF=origin/1.2
 - DB=mysql SYMFONY_REF=origin/1.2
 - DB=sqlite SYMFONY_REF=origin/1.2
